
import Link from 'next/link';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Sparkles, PencilRuler, BookOpenText } from 'lucide-react';

export default function AiTestsPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <header className="text-center mb-12">
        <h1 className="text-4xl font-bold text-primary flex items-center justify-center">
          <Sparkles className="mr-3 h-10 w-10" /> AI Powered Testing Suite
        </h1>
        <p className="text-xl text-muted-foreground mt-2">
          Choose your AI-driven test experience to supercharge your preparation.
        </p>
      </header>

      <div className="grid md:grid-cols-2 gap-8 lg:gap-12">
        {/* Mock Test Card */}
        <Card className="flex flex-col overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300">
          <CardHeader className="p-0">
            <Image
              src="https://placehold.co/600x400.png"
              alt="AI Mock Test illustration"
              width={600}
              height={400}
              className="object-cover w-full h-56"
              data-ai-hint="exam simulation"
            />
          </CardHeader>
          <CardContent className="flex-grow p-6 space-y-3">
            <CardTitle className="text-2xl font-semibold text-foreground flex items-center">
              <PencilRuler className="mr-2 h-6 w-6 text-primary" />
              AI Mock Test
            </CardTitle>
            <CardDescription className="text-base text-muted-foreground">
              Experience a full-length mock test generated by AI, simulating real exam conditions with diverse questions across subjects.
            </CardDescription>
          </CardContent>
          <CardFooter className="p-6 pt-0">
            <Button asChild size="lg" className="w-full bg-primary hover:bg-primary/90 text-primary-foreground">
              <Link href="/mock-test">Take Mock Test</Link>
            </Button>
          </CardFooter>
        </Card>

        {/* Practice Test Card */}
        <Card className="flex flex-col overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-shadow duration-300">
          <CardHeader className="p-0">
            <Image
              src="https://placehold.co/600x400.png"
              alt="AI Practice Test illustration"
              width={600}
              height={400}
              className="object-cover w-full h-56"
              data-ai-hint="focused practice"
            />
          </CardHeader>
          <CardContent className="flex-grow p-6 space-y-3">
            <CardTitle className="text-2xl font-semibold text-foreground flex items-center">
              <BookOpenText className="mr-2 h-6 w-6 text-accent" />
              AI Practice Test
            </CardTitle>
            <CardDescription className="text-base text-muted-foreground">
              Create personalized practice sessions. Select subjects, chapters, and difficulty to focus on specific areas with AI-generated MCQs.
            </CardDescription>
          </CardContent>
          <CardFooter className="p-6 pt-0">
            <Button asChild size="lg" className="w-full bg-accent hover:bg-accent/90 text-accent-foreground">
              <Link href="/practice-test">Create Practice Test</Link>
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}
